/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.newvi.sic.web.enums;

/**
 *
 * @author israelavila
 */
public enum EnumEtiquetas {
    
    GENERICO_LISTA_TITULO("Administración"),
    GENERICO_LISTA_ICONO("fa fa-table"),
    GENERICO_LISTA_DESCRIPCION("Gestión de elementos."),
    GENERICO_NUEVO_TITULO("Nuevo"),
    GENERICO_NUEVO_ICONO("fa-plus"),
    GENERICO_NUEVO_DESCRIPCION("Creación de nuevos elementos."),
    GENERICO_EDITAR_TITULO("Editar"),
    GENERICO_EDITAR_ICONO("fa fa-edit"),
    GENERICO_EDITAR_DESCRIPCION("Edición de elementos."),
    USUARIOS_LISTA_TITULO("Usuarios"),
    USUARIOS_LISTA_ICONO("fa fa-users"),
    USUARIOS_LISTA_DESCRIPCION("Gestión de usuarios en el sistema."),
    USUARIOS_NUEVO_TITULO("Nuevo Usuario"),
    USUARIOS_NUEVO_ICONO("fa fa-user-plus"),
    USUARIOS_NUEVO_DESCRIPCION("Creación de nuevo usuario."),
    USUARIOS_EDITAR_TITULO("Editar Usuario"),
    USUARIOS_EDITAR_ICONO("fa fa-user"),
    USUARIOS_EDITAR_DESCRIPCION("Edición de usuario seleccionado."),
    DOMINIOS_LISTA_TITULO("Dominios"),
    DOMINIOS_LISTA_ICONO("fa fa-leanpub"),
    DOMINIOS_LISTA_DESCRIPCION("Gestión de dominios en el sistema."),
    DOMINIOS_NUEVO_TITULO("Nuevo Dominio"),
    DOMINIOS_NUEVO_ICONO("fa fa-plus"),
    DOMINIOS_NUEVO_DESCRIPCION("Creación de nuevo dominio."),
    DOMINIOS_EDITAR_TITULO("Editar Dominio"),
    DOMINIOS_EDITAR_ICONO("fa fa-edit"),
    DOMINIOS_EDITAR_DESCRIPCION("Edición de dominio seleccionado."),
    FUNCIONALIDADES_LISTA_TITULO("Funcionalidades"),
    FUNCIONALIDADES_LISTA_ICONO("fa fa-gears"),
    FUNCIONALIDADES_LISTA_DESCRIPCION("Gestión de funcionalidades en el sistema."),
    FUNCIONALIDADES_NUEVO_TITULO("Nueva Funcionalidad"),
    FUNCIONALIDADES_NUEVO_ICONO("fa fa-plus"),
    FUNCIONALIDADES_NUEVO_DESCRIPCION("Creación de nueva funcionalidad."),
    FUNCIONALIDADES_SUB_NUEVO_TITULO("Nueva Subfuncionalidad"),
    FUNCIONALIDADES_SUB_NUEVO_ICONO("fa fa-plus"),
    FUNCIONALIDADES_SUB_NUEVO_DESCRIPCION("Creación de nueva subfuncionalidad."),
    FUNCIONALIDADES_EDITAR_TITULO("Editar Funcionalidad"),
    FUNCIONALIDADES_EDITAR_ICONO("fa fa-edit"),
    FUNCIONALIDADES_EDITAR_DESCRIPCION("Edición de funcionalidad seleccionado."),
    PERMISOS_LISTA_TITULO("Roles y Permisos"),
    PERMISOS_LISTA_ICONO("fa fa-user-secret"),
    PERMISOS_LISTA_DESCRIPCION("Gestión de permisos en el sistema."),
    PERMISOS_NUEVO_TITULO("Nuevo Permiso"),
    PERMISOS_NUEVO_ICONO("fa fa-plus"),
    PERMISOS_NUEVO_DESCRIPCION("Creación de nueva permiso."),
    PERMISOS_EDITAR_TITULO("Editar Permiso"),
    PERMISOS_EDITAR_ICONO("fa fa-edit"),
    PERMISOS_EDITAR_DESCRIPCION("Edición de permiso seleccionado."),
    PERMISOS_ASIGNAR_TITULO("Asignar funcionalidades al rol"),
    PERMISOS_ASIGNAR_ICONO("fa fa-check-square-o"),
    PERMISOS_ASIGNAR_DESCRIPCION("Asignación de funcionalidades permitidas al rol seleccionado."),
    CONTRIBUYENTES_LISTA_TITULO("Gestión de Contribuyentes"),
    CONTRIBUYENTES_LISTA_ICONO("fa fa-users"),
    CONTRIBUYENTES_LISTA_DESCRIPCION("Gestión de contribuyentes en el sistema."),
    CONTRIBUYENTES_NUEVO_TITULO("Nuevo Contribuyente"),
    CONTRIBUYENTES_NUEVO_ICONO("fa fa-plus"),
    CONTRIBUYENTES_NUEVO_DESCRIPCION("Creación de nuevo contribuyente."),
    CONTRIBUYENTES_EDITAR_TITULO("Editar Contribuyente"),
    CONTRIBUYENTES_EDITAR_ICONO("fa fa-edit"),
    CONTRIBUYENTES_EDITAR_DESCRIPCION("Edición de contribuyente seleccionado."),
    CONTRIBUCION_MEJORAS_LISTA_TITULO("Contribucion Especial de Mejoras"),
    CONTRIBUCION_MEJORAS_LISTA_ICONO("fa fa-thumbs-o-up"),
    CONTRIBUCION_MEJORAS_LISTA_DESCRIPCION("Gestión de Contribucion Especial de Mejoras en el sistema."),
    CONTRIBUCION_MEJORAS_NUEVO_TITULO("Nueva Contribucion Especial de Mejora"),
    CONTRIBUCION_MEJORAS_NUEVO_ICONO("fa fa-plus"),
    CONTRIBUCION_MEJORAS_NUEVO_DESCRIPCION("Creación de nueva Contribucion Especial de Mejora."),
    CONTRIBUCION_MEJORAS_EDITAR_TITULO("Editar Contribucion Especial de Mejora"),
    CONTRIBUCION_MEJORAS_EDITAR_ICONO("fa fa-edit"),
    CONTRIBUCION_MEJORAS_EDITAR_DESCRIPCION("Edición de Contribucion Especial de Mejora seleccionado."),
    FICHA_CATASTRAL_LISTA_TITULO("Ficha Predial Urbana"),
    FICHA_CATASTRAL_LISTA_ICONO("fa fa-list-alt"),
    FICHA_CATASTRAL_LISTA_DESCRIPCION("Gestión de ficha predial urbana."),
    FICHA_CATASTRAL_NUEVO_TITULO("Nueva Ficha Predial"),
    FICHA_CATASTRAL_NUEVO_ICONO("fa fa-plus"),
    FICHA_CATASTRAL_NUEVO_DESCRIPCION("Creación de nueva Ficha Predial."),
    FICHA_CATASTRAL_EDITAR_TITULO("Editar Ficha Predial"),
    FICHA_CATASTRAL_EDITAR_ICONO("fa fa-edit"),
    FICHA_CATASTRAL_EDITAR_DESCRIPCION("Edición de Ficha Predial seleccionada."),
    FICHA_CATASTRAL_LISTA_EDITAR_TITULO("Lista de Fichas Prediales Editables"),
    FICHA_CATASTRAL_LISTA_EDITAR_ICONO("fa fa-edit"),
    FICHA_CATASTRAL_LISTA_EDITAR_DESCRIPCION("Edición de Fichas Prediales."),
    FICHA_CATASTRAL_LISTA_ELIMINAR_TITULO("Lista de Fichas Prediales Eliminables"),
    FICHA_CATASTRAL_LISTA_ELIMINAR_ICONO("fa fa-trash"),
    FICHA_CATASTRAL_LISTA_ELIMINAR_DESCRIPCION("Eliminacion de Fichas Prediales."),
    BLOQUES_LISTA_TITULO("Bloques"),
    BLOQUES_LISTA_ICONO("fa fa-square"),
    BLOQUES_LISTA_DESCRIPCION("Gestión de bloques."),
    BLOQUES_NUEVO_TITULO("Nueva Bloque"),
    BLOQUES_NUEVO_ICONO("fa fa-plus"),
    BLOQUES_NUEVO_DESCRIPCION("Creación de nuevo Bloque."),
    BLOQUES_EDITAR_TITULO("Editar Bloque"),
    BLOQUES_EDITAR_ICONO("fa fa-edit"),
    BLOQUES_EDITAR_DESCRIPCION("Edición de Bloques seleccionado."),
    PISOS_LISTA_TITULO("Pisos"),
    PISOS_LISTA_ICONO("fa fa-align-justify"),
    PISOS_LISTA_DESCRIPCION("Gestión de pisos."),
    PISOS_NUEVO_TITULO("Nueva Piso"),
    PISOS_NUEVO_ICONO("fa fa-plus"),
    PISOS_NUEVO_DESCRIPCION("Creación de nuevo Piso."),
    PISOS_EDITAR_TITULO("Editar Piso"),
    PISOS_EDITAR_ICONO("fa fa-edit"),
    PISOS_EDITAR_DESCRIPCION("Edición de Pisos seleccionado."),
    PROPIETARIO_LISTA_TITULO("Propietario"),
    PROPIETARIO_LISTA_ICONO("fa fa-home"),
    PROPIETARIO_LISTA_DESCRIPCION("Gestión de propietarios."),
    PROPIETARIO_NUEVO_TITULO("Nueva Propietario"),
    PROPIETARIO_NUEVO_ICONO("fa fa-plus"),
    PROPIETARIO_NUEVO_DESCRIPCION("Creación de nuevo Propietario."),
    PROPIETARIO_EDITAR_TITULO("Editar Propietario"),
    PROPIETARIO_EDITAR_ICONO("fa fa-edit"),
    PROPIETARIO_EDITAR_DESCRIPCION("Edición de Propietario seleccionado."),
    SIMULACION_LISTA_TITULO("Simulación"),
    SIMULACION_LISTA_ICONO("fa fa-laptop"),
    SIMULACION_LISTA_DESCRIPCION("Gestión de simulacion"),
    PARAMETROS_LISTA_TITULO("Parametros para calculo"),
    PARAMETROS_LISTA_ICONO("fa fa-calculator"),
    PARAMETROS_LISTA_DESCRIPCION("Gestión de parametros."),
    PARAMETROS_NUEVO_TITULO("Nuevo Parametro"),
    PARAMETROS_NUEVO_ICONO("fa fa-plus"),
    PARAMETROS_NUEVO_DESCRIPCION("Creación de nuevo Parametro."),
    PARAMETROS_EDITAR_TITULO("Editar Parametro"),
    PARAMETROS_EDITAR_ICONO("fa fa-edit"),
    PARAMETROS_EDITAR_DESCRIPCION("Edición de Parametros seleccionado."),
    FORMULARIO_ECONOMICO_LISTA_TITULO("Formulario Económico"),
    FORMULARIO_ECONOMICO_LISTA_ICONO("fa fa-money"),
    FORMULARIO_ECONOMICO_LISTA_DESCRIPCION("Gestión de formularios económicos."),
    PARAMETROS_SISTEMA_LISTA_TITULO("Parámetros del Sistema"),
    PARAMETROS_SISTEMA_LISTA_ICONO("fa fa-list-ul"),
    PARAMETROS_SISTEMA_LISTA_DESCRIPCION("Gestión de Parámetros en el sistema SIGC."),
    PARAMETROS_SISTEMA_NUEVO_TITULO("Nuevo Parámetro del sistema"),
    PARAMETROS_SISTEMA_NUEVO_ICONO("fa fa-plus"),
    PARAMETROS_SISTEMA_NUEVO_DESCRIPCION("Creación de nuevo Parametro del Sistema."),
    PARAMETROS_SISTEMA_EDITAR_TITULO("Editar Parámetro del Sistema"),
    PARAMETROS_SISTEMA_EDITAR_ICONO("fa fa-edit"),
    PARAMETROS_SISTEMA_EDITAR_DESCRIPCION("Edición de Parámetros seleccionado.");
    
    private final String textoEtiqueta;

    public String getTextoEtiqueta() {
        return textoEtiqueta;
    }
    
    private EnumEtiquetas(String textoEtiqueta) {
        this.textoEtiqueta = textoEtiqueta;
    }
}
